
version: '3'
services:
  msg_api:
    image: msg_api:v1.4
    ports:
      - "5000:5000"

    networks:
      - mymsgapinet

  mymongodb:

    image: mymongo:v1.0
    ports:
      - "27017:27017"

    networks:
      mymsgapinet:
        aliases:
          - zedsmongodb

  msg_rcvr:

    image: msg_rcvr:v1.3

    networks:
      - mymsgapinet

  myrabbit:
    image: myrabbit:v1.1
    ports:
      - 5672:5672
      - 15672:15672

    networks:
      mymsgapinet:
        aliases:
          - zedsmongodb


networks:
  mymsgapinet:


# next step
  # build image for mongo - add that to services list here and also set the networks attribute on it
  # test the 'post' operation :)  !!!
