
version: '3'
services:

  msg_rcvr:
    image: msg_rcvr:v1.3

    networks:
      mymsgapinet:
        aliases:
          - zedsmongodb

  mynginx:
    image: mynginx:v1.6
    ports:
      - 8882:8882

    networks:
      mymsgapinet:
        aliases:
          - zedsmongodb

networks:
  mymsgapinet:


# next step
  # build image for mongo - add that to services list here and also set the networks attribute on it
  # test the 'post' operation :)  !!!
